# Generated by Django 5.2.11 on 2026-02-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='google_maps_embed_url',
            field=models.URLField(blank=True, help_text='Paste the full Google Maps embed URL for the Contact page map.', max_length=1000),
        ),
    ]
