# Generated by Django 5.2.11 on 2026-02-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sitesetting_google_maps_embed_url'),
    ]

    operations = [
       
    ]
