# Generated by Django 5.2.11 on 2026-02-27 10:37

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_heroslide_background_video'),
    ]

    operations = [
        
    ]
