# Generated by Django 5.2.11 on 2026-02-27 10:37

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_heroslide_background_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='background_video',
            field=models.FileField(blank=True, help_text='Upload an MP4/WebM video. If set, it will be used instead of the background image.', null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='hero_slides/videos/'),
        ),
    ]
